#!/bin/sh -e

PUBKEY_URL=https://raw.github.com/hashicorp/vagrant/master/keys/vagrant.pub

chrootcmd='chroot /target'

${chrootcmd} mkdir -vp /home/vagrant/.ssh
${chrootcmd} wget -q -O /home/vagrant/.ssh/authorized_keys ${PUBKEY_URL}
${chrootcmd} chmod 0640 /home/vagrant/.ssh/authorized_keys
${chrootcmd} chmod 0750 /home/vagrant/.ssh
${chrootcmd} chown -vR vagrant:vagrant /home/vagrant/.ssh

exit 0
