#!/bin/sh -e

logf=/target/root/late_command.log
srcdir=`dirname $(realpath $0)`

date -R >$logf
ls ${srcdir}/???-* | sort >>$logf
echo '---' >>$logf

for s in `ls ${srcdir}/???-* | sort`; do
    echo "--- ${s}" >>$logf 2>>$logf
    /bin/sh -xe ${s} >>$logf 2>>$logf
done

rm -f /target/root/late_command.log
exit 0
